// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/allocation_description.proto

package tensorflow;

public final class AllocationDescriptionOuterClass {
  private AllocationDescriptionOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AllocationDescriptionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tensorflow.AllocationDescription)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 requested_bytes = 1;</code>
     *
     * <pre>
     * Total number of bytes requested
     * </pre>
     */
    long getRequestedBytes();

    /**
     * <code>optional int64 allocated_bytes = 2;</code>
     *
     * <pre>
     * Total number of bytes allocated if known
     * </pre>
     */
    long getAllocatedBytes();

    /**
     * <code>optional string allocator_name = 3;</code>
     *
     * <pre>
     * Name of the allocator used
     * </pre>
     */
    java.lang.String getAllocatorName();
    /**
     * <code>optional string allocator_name = 3;</code>
     *
     * <pre>
     * Name of the allocator used
     * </pre>
     */
    com.google.protobuf.ByteString
        getAllocatorNameBytes();
  }
  /**
   * Protobuf type {@code tensorflow.AllocationDescription}
   */
  public  static final class AllocationDescription extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:tensorflow.AllocationDescription)
      AllocationDescriptionOrBuilder {
    // Use AllocationDescription.newBuilder() to construct.
    private AllocationDescription(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private AllocationDescription() {
      requestedBytes_ = 0L;
      allocatedBytes_ = 0L;
      allocatorName_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private AllocationDescription(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              requestedBytes_ = input.readInt64();
              break;
            }
            case 16: {

              allocatedBytes_ = input.readInt64();
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              allocatorName_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tensorflow.AllocationDescriptionOuterClass.internal_static_tensorflow_AllocationDescription_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tensorflow.AllocationDescriptionOuterClass.internal_static_tensorflow_AllocationDescription_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tensorflow.AllocationDescriptionOuterClass.AllocationDescription.class, tensorflow.AllocationDescriptionOuterClass.AllocationDescription.Builder.class);
    }

    public static final int REQUESTED_BYTES_FIELD_NUMBER = 1;
    private long requestedBytes_;
    /**
     * <code>optional int64 requested_bytes = 1;</code>
     *
     * <pre>
     * Total number of bytes requested
     * </pre>
     */
    public long getRequestedBytes() {
      return requestedBytes_;
    }

    public static final int ALLOCATED_BYTES_FIELD_NUMBER = 2;
    private long allocatedBytes_;
    /**
     * <code>optional int64 allocated_bytes = 2;</code>
     *
     * <pre>
     * Total number of bytes allocated if known
     * </pre>
     */
    public long getAllocatedBytes() {
      return allocatedBytes_;
    }

    public static final int ALLOCATOR_NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object allocatorName_;
    /**
     * <code>optional string allocator_name = 3;</code>
     *
     * <pre>
     * Name of the allocator used
     * </pre>
     */
    public java.lang.String getAllocatorName() {
      java.lang.Object ref = allocatorName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        allocatorName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string allocator_name = 3;</code>
     *
     * <pre>
     * Name of the allocator used
     * </pre>
     */
    public com.google.protobuf.ByteString
        getAllocatorNameBytes() {
      java.lang.Object ref = allocatorName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        allocatorName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (requestedBytes_ != 0L) {
        output.writeInt64(1, requestedBytes_);
      }
      if (allocatedBytes_ != 0L) {
        output.writeInt64(2, allocatedBytes_);
      }
      if (!getAllocatorNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, allocatorName_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (requestedBytes_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, requestedBytes_);
      }
      if (allocatedBytes_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, allocatedBytes_);
      }
      if (!getAllocatorNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, allocatorName_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static tensorflow.AllocationDescriptionOuterClass.AllocationDescription parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tensorflow.AllocationDescriptionOuterClass.AllocationDescription parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tensorflow.AllocationDescriptionOuterClass.AllocationDescription parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tensorflow.AllocationDescriptionOuterClass.AllocationDescription parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tensorflow.AllocationDescriptionOuterClass.AllocationDescription parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static tensorflow.AllocationDescriptionOuterClass.AllocationDescription parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static tensorflow.AllocationDescriptionOuterClass.AllocationDescription parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static tensorflow.AllocationDescriptionOuterClass.AllocationDescription parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static tensorflow.AllocationDescriptionOuterClass.AllocationDescription parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static tensorflow.AllocationDescriptionOuterClass.AllocationDescription parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(tensorflow.AllocationDescriptionOuterClass.AllocationDescription prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tensorflow.AllocationDescription}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tensorflow.AllocationDescription)
        tensorflow.AllocationDescriptionOuterClass.AllocationDescriptionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tensorflow.AllocationDescriptionOuterClass.internal_static_tensorflow_AllocationDescription_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tensorflow.AllocationDescriptionOuterClass.internal_static_tensorflow_AllocationDescription_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tensorflow.AllocationDescriptionOuterClass.AllocationDescription.class, tensorflow.AllocationDescriptionOuterClass.AllocationDescription.Builder.class);
      }

      // Construct using tensorflow.AllocationDescriptionOuterClass.AllocationDescription.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        requestedBytes_ = 0L;

        allocatedBytes_ = 0L;

        allocatorName_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tensorflow.AllocationDescriptionOuterClass.internal_static_tensorflow_AllocationDescription_descriptor;
      }

      public tensorflow.AllocationDescriptionOuterClass.AllocationDescription getDefaultInstanceForType() {
        return tensorflow.AllocationDescriptionOuterClass.AllocationDescription.getDefaultInstance();
      }

      public tensorflow.AllocationDescriptionOuterClass.AllocationDescription build() {
        tensorflow.AllocationDescriptionOuterClass.AllocationDescription result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public tensorflow.AllocationDescriptionOuterClass.AllocationDescription buildPartial() {
        tensorflow.AllocationDescriptionOuterClass.AllocationDescription result = new tensorflow.AllocationDescriptionOuterClass.AllocationDescription(this);
        result.requestedBytes_ = requestedBytes_;
        result.allocatedBytes_ = allocatedBytes_;
        result.allocatorName_ = allocatorName_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tensorflow.AllocationDescriptionOuterClass.AllocationDescription) {
          return mergeFrom((tensorflow.AllocationDescriptionOuterClass.AllocationDescription)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tensorflow.AllocationDescriptionOuterClass.AllocationDescription other) {
        if (other == tensorflow.AllocationDescriptionOuterClass.AllocationDescription.getDefaultInstance()) return this;
        if (other.getRequestedBytes() != 0L) {
          setRequestedBytes(other.getRequestedBytes());
        }
        if (other.getAllocatedBytes() != 0L) {
          setAllocatedBytes(other.getAllocatedBytes());
        }
        if (!other.getAllocatorName().isEmpty()) {
          allocatorName_ = other.allocatorName_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        tensorflow.AllocationDescriptionOuterClass.AllocationDescription parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (tensorflow.AllocationDescriptionOuterClass.AllocationDescription) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long requestedBytes_ ;
      /**
       * <code>optional int64 requested_bytes = 1;</code>
       *
       * <pre>
       * Total number of bytes requested
       * </pre>
       */
      public long getRequestedBytes() {
        return requestedBytes_;
      }
      /**
       * <code>optional int64 requested_bytes = 1;</code>
       *
       * <pre>
       * Total number of bytes requested
       * </pre>
       */
      public Builder setRequestedBytes(long value) {
        
        requestedBytes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 requested_bytes = 1;</code>
       *
       * <pre>
       * Total number of bytes requested
       * </pre>
       */
      public Builder clearRequestedBytes() {
        
        requestedBytes_ = 0L;
        onChanged();
        return this;
      }

      private long allocatedBytes_ ;
      /**
       * <code>optional int64 allocated_bytes = 2;</code>
       *
       * <pre>
       * Total number of bytes allocated if known
       * </pre>
       */
      public long getAllocatedBytes() {
        return allocatedBytes_;
      }
      /**
       * <code>optional int64 allocated_bytes = 2;</code>
       *
       * <pre>
       * Total number of bytes allocated if known
       * </pre>
       */
      public Builder setAllocatedBytes(long value) {
        
        allocatedBytes_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 allocated_bytes = 2;</code>
       *
       * <pre>
       * Total number of bytes allocated if known
       * </pre>
       */
      public Builder clearAllocatedBytes() {
        
        allocatedBytes_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object allocatorName_ = "";
      /**
       * <code>optional string allocator_name = 3;</code>
       *
       * <pre>
       * Name of the allocator used
       * </pre>
       */
      public java.lang.String getAllocatorName() {
        java.lang.Object ref = allocatorName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          allocatorName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string allocator_name = 3;</code>
       *
       * <pre>
       * Name of the allocator used
       * </pre>
       */
      public com.google.protobuf.ByteString
          getAllocatorNameBytes() {
        java.lang.Object ref = allocatorName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          allocatorName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string allocator_name = 3;</code>
       *
       * <pre>
       * Name of the allocator used
       * </pre>
       */
      public Builder setAllocatorName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        allocatorName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string allocator_name = 3;</code>
       *
       * <pre>
       * Name of the allocator used
       * </pre>
       */
      public Builder clearAllocatorName() {
        
        allocatorName_ = getDefaultInstance().getAllocatorName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string allocator_name = 3;</code>
       *
       * <pre>
       * Name of the allocator used
       * </pre>
       */
      public Builder setAllocatorNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        allocatorName_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:tensorflow.AllocationDescription)
    }

    // @@protoc_insertion_point(class_scope:tensorflow.AllocationDescription)
    private static final tensorflow.AllocationDescriptionOuterClass.AllocationDescription DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new tensorflow.AllocationDescriptionOuterClass.AllocationDescription();
    }

    public static tensorflow.AllocationDescriptionOuterClass.AllocationDescription getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AllocationDescription>
        PARSER = new com.google.protobuf.AbstractParser<AllocationDescription>() {
      public AllocationDescription parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new AllocationDescription(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<AllocationDescription> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AllocationDescription> getParserForType() {
      return PARSER;
    }

    public tensorflow.AllocationDescriptionOuterClass.AllocationDescription getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_AllocationDescription_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tensorflow_AllocationDescription_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n6tensorflow/core/framework/allocation_d" +
      "escription.proto\022\ntensorflow\"a\n\025Allocati" +
      "onDescription\022\027\n\017requested_bytes\030\001 \001(\003\022\027" +
      "\n\017allocated_bytes\030\002 \001(\003\022\026\n\016allocator_nam" +
      "e\030\003 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tensorflow_AllocationDescription_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tensorflow_AllocationDescription_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tensorflow_AllocationDescription_descriptor,
        new java.lang.String[] { "RequestedBytes", "AllocatedBytes", "AllocatorName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
