// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/device_attributes.proto

package tensorflow;

public final class DeviceAttributesOuterClass {
  private DeviceAttributesOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code tensorflow.BusAdjacency}
   *
   * <pre>
   * BusAdjacency identifies the ability of a device to participate in
   * maximally efficient DMA operations within the local context of a
   * process.
   * This is currently ignored.
   * </pre>
   */
  public enum BusAdjacency
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>BUS_0 = 0;</code>
     */
    BUS_0(0, 0),
    /**
     * <code>BUS_1 = 1;</code>
     */
    BUS_1(1, 1),
    /**
     * <code>BUS_ANY = 2;</code>
     */
    BUS_ANY(2, 2),
    /**
     * <code>BUS_NUM_ADJACENCIES = 3;</code>
     */
    BUS_NUM_ADJACENCIES(3, 3),
    UNRECOGNIZED(-1, -1),
    ;

    /**
     * <code>BUS_0 = 0;</code>
     */
    public static final int BUS_0_VALUE = 0;
    /**
     * <code>BUS_1 = 1;</code>
     */
    public static final int BUS_1_VALUE = 1;
    /**
     * <code>BUS_ANY = 2;</code>
     */
    public static final int BUS_ANY_VALUE = 2;
    /**
     * <code>BUS_NUM_ADJACENCIES = 3;</code>
     */
    public static final int BUS_NUM_ADJACENCIES_VALUE = 3;


    public final int getNumber() {
      if (index == -1) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    public static BusAdjacency valueOf(int value) {
      switch (value) {
        case 0: return BUS_0;
        case 1: return BUS_1;
        case 2: return BUS_ANY;
        case 3: return BUS_NUM_ADJACENCIES;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<BusAdjacency>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        BusAdjacency> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<BusAdjacency>() {
            public BusAdjacency findValueByNumber(int number) {
              return BusAdjacency.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return tensorflow.DeviceAttributesOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final BusAdjacency[] VALUES = values();

    public static BusAdjacency valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private BusAdjacency(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:tensorflow.BusAdjacency)
  }

  public interface DeviceAttributesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tensorflow.DeviceAttributes)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string device_type = 2;</code>
     *
     * <pre>
     * String representation of device_type.
     * </pre>
     */
    java.lang.String getDeviceType();
    /**
     * <code>optional string device_type = 2;</code>
     *
     * <pre>
     * String representation of device_type.
     * </pre>
     */
    com.google.protobuf.ByteString
        getDeviceTypeBytes();

    /**
     * <code>optional int64 memory_limit = 4;</code>
     *
     * <pre>
     * Memory capacity of device in bytes.
     * </pre>
     */
    long getMemoryLimit();

    /**
     * <code>optional .tensorflow.BusAdjacency bus_adjacency = 5;</code>
     */
    int getBusAdjacencyValue();
    /**
     * <code>optional .tensorflow.BusAdjacency bus_adjacency = 5;</code>
     */
    tensorflow.DeviceAttributesOuterClass.BusAdjacency getBusAdjacency();

    /**
     * <code>optional fixed64 incarnation = 6;</code>
     *
     * <pre>
     * A device is assigned a global unique number each time it is
     * initialized. "incarnation" should never be 0.
     * </pre>
     */
    long getIncarnation();

    /**
     * <code>optional string physical_device_desc = 7;</code>
     *
     * <pre>
     * String representation of the physical device that this device maps to.
     * </pre>
     */
    java.lang.String getPhysicalDeviceDesc();
    /**
     * <code>optional string physical_device_desc = 7;</code>
     *
     * <pre>
     * String representation of the physical device that this device maps to.
     * </pre>
     */
    com.google.protobuf.ByteString
        getPhysicalDeviceDescBytes();
  }
  /**
   * Protobuf type {@code tensorflow.DeviceAttributes}
   */
  public  static final class DeviceAttributes extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:tensorflow.DeviceAttributes)
      DeviceAttributesOrBuilder {
    // Use DeviceAttributes.newBuilder() to construct.
    private DeviceAttributes(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private DeviceAttributes() {
      name_ = "";
      deviceType_ = "";
      memoryLimit_ = 0L;
      busAdjacency_ = 0;
      incarnation_ = 0L;
      physicalDeviceDesc_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private DeviceAttributes(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              deviceType_ = s;
              break;
            }
            case 32: {

              memoryLimit_ = input.readInt64();
              break;
            }
            case 40: {
              int rawValue = input.readEnum();

              busAdjacency_ = rawValue;
              break;
            }
            case 49: {

              incarnation_ = input.readFixed64();
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              physicalDeviceDesc_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tensorflow.DeviceAttributesOuterClass.internal_static_tensorflow_DeviceAttributes_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tensorflow.DeviceAttributesOuterClass.internal_static_tensorflow_DeviceAttributes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tensorflow.DeviceAttributesOuterClass.DeviceAttributes.class, tensorflow.DeviceAttributesOuterClass.DeviceAttributes.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICE_TYPE_FIELD_NUMBER = 2;
    private volatile java.lang.Object deviceType_;
    /**
     * <code>optional string device_type = 2;</code>
     *
     * <pre>
     * String representation of device_type.
     * </pre>
     */
    public java.lang.String getDeviceType() {
      java.lang.Object ref = deviceType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceType_ = s;
        return s;
      }
    }
    /**
     * <code>optional string device_type = 2;</code>
     *
     * <pre>
     * String representation of device_type.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getDeviceTypeBytes() {
      java.lang.Object ref = deviceType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MEMORY_LIMIT_FIELD_NUMBER = 4;
    private long memoryLimit_;
    /**
     * <code>optional int64 memory_limit = 4;</code>
     *
     * <pre>
     * Memory capacity of device in bytes.
     * </pre>
     */
    public long getMemoryLimit() {
      return memoryLimit_;
    }

    public static final int BUS_ADJACENCY_FIELD_NUMBER = 5;
    private int busAdjacency_;
    /**
     * <code>optional .tensorflow.BusAdjacency bus_adjacency = 5;</code>
     */
    public int getBusAdjacencyValue() {
      return busAdjacency_;
    }
    /**
     * <code>optional .tensorflow.BusAdjacency bus_adjacency = 5;</code>
     */
    public tensorflow.DeviceAttributesOuterClass.BusAdjacency getBusAdjacency() {
      tensorflow.DeviceAttributesOuterClass.BusAdjacency result = tensorflow.DeviceAttributesOuterClass.BusAdjacency.valueOf(busAdjacency_);
      return result == null ? tensorflow.DeviceAttributesOuterClass.BusAdjacency.UNRECOGNIZED : result;
    }

    public static final int INCARNATION_FIELD_NUMBER = 6;
    private long incarnation_;
    /**
     * <code>optional fixed64 incarnation = 6;</code>
     *
     * <pre>
     * A device is assigned a global unique number each time it is
     * initialized. "incarnation" should never be 0.
     * </pre>
     */
    public long getIncarnation() {
      return incarnation_;
    }

    public static final int PHYSICAL_DEVICE_DESC_FIELD_NUMBER = 7;
    private volatile java.lang.Object physicalDeviceDesc_;
    /**
     * <code>optional string physical_device_desc = 7;</code>
     *
     * <pre>
     * String representation of the physical device that this device maps to.
     * </pre>
     */
    public java.lang.String getPhysicalDeviceDesc() {
      java.lang.Object ref = physicalDeviceDesc_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        physicalDeviceDesc_ = s;
        return s;
      }
    }
    /**
     * <code>optional string physical_device_desc = 7;</code>
     *
     * <pre>
     * String representation of the physical device that this device maps to.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getPhysicalDeviceDescBytes() {
      java.lang.Object ref = physicalDeviceDesc_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        physicalDeviceDesc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
      }
      if (!getDeviceTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, deviceType_);
      }
      if (memoryLimit_ != 0L) {
        output.writeInt64(4, memoryLimit_);
      }
      if (busAdjacency_ != tensorflow.DeviceAttributesOuterClass.BusAdjacency.BUS_0.getNumber()) {
        output.writeEnum(5, busAdjacency_);
      }
      if (incarnation_ != 0L) {
        output.writeFixed64(6, incarnation_);
      }
      if (!getPhysicalDeviceDescBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 7, physicalDeviceDesc_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
      }
      if (!getDeviceTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, deviceType_);
      }
      if (memoryLimit_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, memoryLimit_);
      }
      if (busAdjacency_ != tensorflow.DeviceAttributesOuterClass.BusAdjacency.BUS_0.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, busAdjacency_);
      }
      if (incarnation_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed64Size(6, incarnation_);
      }
      if (!getPhysicalDeviceDescBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(7, physicalDeviceDesc_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static tensorflow.DeviceAttributesOuterClass.DeviceAttributes parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tensorflow.DeviceAttributesOuterClass.DeviceAttributes parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tensorflow.DeviceAttributesOuterClass.DeviceAttributes parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tensorflow.DeviceAttributesOuterClass.DeviceAttributes parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tensorflow.DeviceAttributesOuterClass.DeviceAttributes parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static tensorflow.DeviceAttributesOuterClass.DeviceAttributes parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static tensorflow.DeviceAttributesOuterClass.DeviceAttributes parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static tensorflow.DeviceAttributesOuterClass.DeviceAttributes parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static tensorflow.DeviceAttributesOuterClass.DeviceAttributes parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static tensorflow.DeviceAttributesOuterClass.DeviceAttributes parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(tensorflow.DeviceAttributesOuterClass.DeviceAttributes prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tensorflow.DeviceAttributes}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tensorflow.DeviceAttributes)
        tensorflow.DeviceAttributesOuterClass.DeviceAttributesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tensorflow.DeviceAttributesOuterClass.internal_static_tensorflow_DeviceAttributes_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tensorflow.DeviceAttributesOuterClass.internal_static_tensorflow_DeviceAttributes_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tensorflow.DeviceAttributesOuterClass.DeviceAttributes.class, tensorflow.DeviceAttributesOuterClass.DeviceAttributes.Builder.class);
      }

      // Construct using tensorflow.DeviceAttributesOuterClass.DeviceAttributes.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        deviceType_ = "";

        memoryLimit_ = 0L;

        busAdjacency_ = 0;

        incarnation_ = 0L;

        physicalDeviceDesc_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tensorflow.DeviceAttributesOuterClass.internal_static_tensorflow_DeviceAttributes_descriptor;
      }

      public tensorflow.DeviceAttributesOuterClass.DeviceAttributes getDefaultInstanceForType() {
        return tensorflow.DeviceAttributesOuterClass.DeviceAttributes.getDefaultInstance();
      }

      public tensorflow.DeviceAttributesOuterClass.DeviceAttributes build() {
        tensorflow.DeviceAttributesOuterClass.DeviceAttributes result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public tensorflow.DeviceAttributesOuterClass.DeviceAttributes buildPartial() {
        tensorflow.DeviceAttributesOuterClass.DeviceAttributes result = new tensorflow.DeviceAttributesOuterClass.DeviceAttributes(this);
        result.name_ = name_;
        result.deviceType_ = deviceType_;
        result.memoryLimit_ = memoryLimit_;
        result.busAdjacency_ = busAdjacency_;
        result.incarnation_ = incarnation_;
        result.physicalDeviceDesc_ = physicalDeviceDesc_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tensorflow.DeviceAttributesOuterClass.DeviceAttributes) {
          return mergeFrom((tensorflow.DeviceAttributesOuterClass.DeviceAttributes)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tensorflow.DeviceAttributesOuterClass.DeviceAttributes other) {
        if (other == tensorflow.DeviceAttributesOuterClass.DeviceAttributes.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getDeviceType().isEmpty()) {
          deviceType_ = other.deviceType_;
          onChanged();
        }
        if (other.getMemoryLimit() != 0L) {
          setMemoryLimit(other.getMemoryLimit());
        }
        if (other.busAdjacency_ != 0) {
          setBusAdjacencyValue(other.getBusAdjacencyValue());
        }
        if (other.getIncarnation() != 0L) {
          setIncarnation(other.getIncarnation());
        }
        if (!other.getPhysicalDeviceDesc().isEmpty()) {
          physicalDeviceDesc_ = other.physicalDeviceDesc_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        tensorflow.DeviceAttributesOuterClass.DeviceAttributes parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (tensorflow.DeviceAttributesOuterClass.DeviceAttributes) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object deviceType_ = "";
      /**
       * <code>optional string device_type = 2;</code>
       *
       * <pre>
       * String representation of device_type.
       * </pre>
       */
      public java.lang.String getDeviceType() {
        java.lang.Object ref = deviceType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          deviceType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string device_type = 2;</code>
       *
       * <pre>
       * String representation of device_type.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getDeviceTypeBytes() {
        java.lang.Object ref = deviceType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string device_type = 2;</code>
       *
       * <pre>
       * String representation of device_type.
       * </pre>
       */
      public Builder setDeviceType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string device_type = 2;</code>
       *
       * <pre>
       * String representation of device_type.
       * </pre>
       */
      public Builder clearDeviceType() {
        
        deviceType_ = getDefaultInstance().getDeviceType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string device_type = 2;</code>
       *
       * <pre>
       * String representation of device_type.
       * </pre>
       */
      public Builder setDeviceTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deviceType_ = value;
        onChanged();
        return this;
      }

      private long memoryLimit_ ;
      /**
       * <code>optional int64 memory_limit = 4;</code>
       *
       * <pre>
       * Memory capacity of device in bytes.
       * </pre>
       */
      public long getMemoryLimit() {
        return memoryLimit_;
      }
      /**
       * <code>optional int64 memory_limit = 4;</code>
       *
       * <pre>
       * Memory capacity of device in bytes.
       * </pre>
       */
      public Builder setMemoryLimit(long value) {
        
        memoryLimit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 memory_limit = 4;</code>
       *
       * <pre>
       * Memory capacity of device in bytes.
       * </pre>
       */
      public Builder clearMemoryLimit() {
        
        memoryLimit_ = 0L;
        onChanged();
        return this;
      }

      private int busAdjacency_ = 0;
      /**
       * <code>optional .tensorflow.BusAdjacency bus_adjacency = 5;</code>
       */
      public int getBusAdjacencyValue() {
        return busAdjacency_;
      }
      /**
       * <code>optional .tensorflow.BusAdjacency bus_adjacency = 5;</code>
       */
      public Builder setBusAdjacencyValue(int value) {
        busAdjacency_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .tensorflow.BusAdjacency bus_adjacency = 5;</code>
       */
      public tensorflow.DeviceAttributesOuterClass.BusAdjacency getBusAdjacency() {
        tensorflow.DeviceAttributesOuterClass.BusAdjacency result = tensorflow.DeviceAttributesOuterClass.BusAdjacency.valueOf(busAdjacency_);
        return result == null ? tensorflow.DeviceAttributesOuterClass.BusAdjacency.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .tensorflow.BusAdjacency bus_adjacency = 5;</code>
       */
      public Builder setBusAdjacency(tensorflow.DeviceAttributesOuterClass.BusAdjacency value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        busAdjacency_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .tensorflow.BusAdjacency bus_adjacency = 5;</code>
       */
      public Builder clearBusAdjacency() {
        
        busAdjacency_ = 0;
        onChanged();
        return this;
      }

      private long incarnation_ ;
      /**
       * <code>optional fixed64 incarnation = 6;</code>
       *
       * <pre>
       * A device is assigned a global unique number each time it is
       * initialized. "incarnation" should never be 0.
       * </pre>
       */
      public long getIncarnation() {
        return incarnation_;
      }
      /**
       * <code>optional fixed64 incarnation = 6;</code>
       *
       * <pre>
       * A device is assigned a global unique number each time it is
       * initialized. "incarnation" should never be 0.
       * </pre>
       */
      public Builder setIncarnation(long value) {
        
        incarnation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional fixed64 incarnation = 6;</code>
       *
       * <pre>
       * A device is assigned a global unique number each time it is
       * initialized. "incarnation" should never be 0.
       * </pre>
       */
      public Builder clearIncarnation() {
        
        incarnation_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object physicalDeviceDesc_ = "";
      /**
       * <code>optional string physical_device_desc = 7;</code>
       *
       * <pre>
       * String representation of the physical device that this device maps to.
       * </pre>
       */
      public java.lang.String getPhysicalDeviceDesc() {
        java.lang.Object ref = physicalDeviceDesc_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          physicalDeviceDesc_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string physical_device_desc = 7;</code>
       *
       * <pre>
       * String representation of the physical device that this device maps to.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getPhysicalDeviceDescBytes() {
        java.lang.Object ref = physicalDeviceDesc_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          physicalDeviceDesc_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string physical_device_desc = 7;</code>
       *
       * <pre>
       * String representation of the physical device that this device maps to.
       * </pre>
       */
      public Builder setPhysicalDeviceDesc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        physicalDeviceDesc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string physical_device_desc = 7;</code>
       *
       * <pre>
       * String representation of the physical device that this device maps to.
       * </pre>
       */
      public Builder clearPhysicalDeviceDesc() {
        
        physicalDeviceDesc_ = getDefaultInstance().getPhysicalDeviceDesc();
        onChanged();
        return this;
      }
      /**
       * <code>optional string physical_device_desc = 7;</code>
       *
       * <pre>
       * String representation of the physical device that this device maps to.
       * </pre>
       */
      public Builder setPhysicalDeviceDescBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        physicalDeviceDesc_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:tensorflow.DeviceAttributes)
    }

    // @@protoc_insertion_point(class_scope:tensorflow.DeviceAttributes)
    private static final tensorflow.DeviceAttributesOuterClass.DeviceAttributes DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new tensorflow.DeviceAttributesOuterClass.DeviceAttributes();
    }

    public static tensorflow.DeviceAttributesOuterClass.DeviceAttributes getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DeviceAttributes>
        PARSER = new com.google.protobuf.AbstractParser<DeviceAttributes>() {
      public DeviceAttributes parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new DeviceAttributes(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<DeviceAttributes> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DeviceAttributes> getParserForType() {
      return PARSER;
    }

    public tensorflow.DeviceAttributesOuterClass.DeviceAttributes getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_DeviceAttributes_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tensorflow_DeviceAttributes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n1tensorflow/core/framework/device_attri" +
      "butes.proto\022\ntensorflow\"\257\001\n\020DeviceAttrib" +
      "utes\022\014\n\004name\030\001 \001(\t\022\023\n\013device_type\030\002 \001(\t\022" +
      "\024\n\014memory_limit\030\004 \001(\003\022/\n\rbus_adjacency\030\005" +
      " \001(\0162\030.tensorflow.BusAdjacency\022\023\n\013incarn" +
      "ation\030\006 \001(\006\022\034\n\024physical_device_desc\030\007 \001(" +
      "\t*J\n\014BusAdjacency\022\t\n\005BUS_0\020\000\022\t\n\005BUS_1\020\001\022" +
      "\013\n\007BUS_ANY\020\002\022\027\n\023BUS_NUM_ADJACENCIES\020\003b\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tensorflow_DeviceAttributes_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tensorflow_DeviceAttributes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tensorflow_DeviceAttributes_descriptor,
        new java.lang.String[] { "Name", "DeviceType", "MemoryLimit", "BusAdjacency", "Incarnation", "PhysicalDeviceDesc", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
