// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/kernel_def.proto

package tensorflow;

public final class KernelDefOuterClass {
  private KernelDefOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface KernelDefOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tensorflow.KernelDef)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string op = 1;</code>
     *
     * <pre>
     * Must match the name of an Op.
     * </pre>
     */
    java.lang.String getOp();
    /**
     * <code>optional string op = 1;</code>
     *
     * <pre>
     * Must match the name of an Op.
     * </pre>
     */
    com.google.protobuf.ByteString
        getOpBytes();

    /**
     * <code>optional string device_type = 2;</code>
     *
     * <pre>
     * Type of device this kernel runs on.
     * </pre>
     */
    java.lang.String getDeviceType();
    /**
     * <code>optional string device_type = 2;</code>
     *
     * <pre>
     * Type of device this kernel runs on.
     * </pre>
     */
    com.google.protobuf.ByteString
        getDeviceTypeBytes();

    /**
     * <code>repeated .tensorflow.KernelDef.AttrConstraint constraint = 3;</code>
     */
    java.util.List<tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint> 
        getConstraintList();
    /**
     * <code>repeated .tensorflow.KernelDef.AttrConstraint constraint = 3;</code>
     */
    tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint getConstraint(int index);
    /**
     * <code>repeated .tensorflow.KernelDef.AttrConstraint constraint = 3;</code>
     */
    int getConstraintCount();
    /**
     * <code>repeated .tensorflow.KernelDef.AttrConstraint constraint = 3;</code>
     */
    java.util.List<? extends tensorflow.KernelDefOuterClass.KernelDef.AttrConstraintOrBuilder> 
        getConstraintOrBuilderList();
    /**
     * <code>repeated .tensorflow.KernelDef.AttrConstraint constraint = 3;</code>
     */
    tensorflow.KernelDefOuterClass.KernelDef.AttrConstraintOrBuilder getConstraintOrBuilder(
        int index);

    /**
     * <code>repeated string host_memory_arg = 4;</code>
     *
     * <pre>
     * Names of the Op's input_/output_args that reside in host memory
     * instead of device memory.
     * </pre>
     */
    com.google.protobuf.ProtocolStringList
        getHostMemoryArgList();
    /**
     * <code>repeated string host_memory_arg = 4;</code>
     *
     * <pre>
     * Names of the Op's input_/output_args that reside in host memory
     * instead of device memory.
     * </pre>
     */
    int getHostMemoryArgCount();
    /**
     * <code>repeated string host_memory_arg = 4;</code>
     *
     * <pre>
     * Names of the Op's input_/output_args that reside in host memory
     * instead of device memory.
     * </pre>
     */
    java.lang.String getHostMemoryArg(int index);
    /**
     * <code>repeated string host_memory_arg = 4;</code>
     *
     * <pre>
     * Names of the Op's input_/output_args that reside in host memory
     * instead of device memory.
     * </pre>
     */
    com.google.protobuf.ByteString
        getHostMemoryArgBytes(int index);

    /**
     * <code>optional string label = 5;</code>
     *
     * <pre>
     * This allows experimental kernels to be registered for an op that
     * won't be used unless the user specifies a "_kernel" attr with
     * value matching this.
     * </pre>
     */
    java.lang.String getLabel();
    /**
     * <code>optional string label = 5;</code>
     *
     * <pre>
     * This allows experimental kernels to be registered for an op that
     * won't be used unless the user specifies a "_kernel" attr with
     * value matching this.
     * </pre>
     */
    com.google.protobuf.ByteString
        getLabelBytes();
  }
  /**
   * Protobuf type {@code tensorflow.KernelDef}
   */
  public  static final class KernelDef extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:tensorflow.KernelDef)
      KernelDefOrBuilder {
    // Use KernelDef.newBuilder() to construct.
    private KernelDef(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private KernelDef() {
      op_ = "";
      deviceType_ = "";
      constraint_ = java.util.Collections.emptyList();
      hostMemoryArg_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      label_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private KernelDef(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              op_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              deviceType_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                constraint_ = new java.util.ArrayList<tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint>();
                mutable_bitField0_ |= 0x00000004;
              }
              constraint_.add(input.readMessage(tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint.parser(), extensionRegistry));
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                hostMemoryArg_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              hostMemoryArg_.add(s);
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              label_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          constraint_ = java.util.Collections.unmodifiableList(constraint_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          hostMemoryArg_ = hostMemoryArg_.getUnmodifiableView();
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tensorflow.KernelDefOuterClass.internal_static_tensorflow_KernelDef_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tensorflow.KernelDefOuterClass.internal_static_tensorflow_KernelDef_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tensorflow.KernelDefOuterClass.KernelDef.class, tensorflow.KernelDefOuterClass.KernelDef.Builder.class);
    }

    public interface AttrConstraintOrBuilder extends
        // @@protoc_insertion_point(interface_extends:tensorflow.KernelDef.AttrConstraint)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional string name = 1;</code>
       *
       * <pre>
       * Name of an attr from the Op.
       * </pre>
       */
      java.lang.String getName();
      /**
       * <code>optional string name = 1;</code>
       *
       * <pre>
       * Name of an attr from the Op.
       * </pre>
       */
      com.google.protobuf.ByteString
          getNameBytes();

      /**
       * <code>optional .tensorflow.AttrValue allowed_values = 2;</code>
       *
       * <pre>
       * A list of values that this kernel supports for this attr.
       * Like OpDef.AttrDef.allowed_values, except for kernels instead of Ops.
       * </pre>
       */
      boolean hasAllowedValues();
      /**
       * <code>optional .tensorflow.AttrValue allowed_values = 2;</code>
       *
       * <pre>
       * A list of values that this kernel supports for this attr.
       * Like OpDef.AttrDef.allowed_values, except for kernels instead of Ops.
       * </pre>
       */
      tensorflow.AttrValueOuterClass.AttrValue getAllowedValues();
      /**
       * <code>optional .tensorflow.AttrValue allowed_values = 2;</code>
       *
       * <pre>
       * A list of values that this kernel supports for this attr.
       * Like OpDef.AttrDef.allowed_values, except for kernels instead of Ops.
       * </pre>
       */
      tensorflow.AttrValueOuterClass.AttrValueOrBuilder getAllowedValuesOrBuilder();
    }
    /**
     * Protobuf type {@code tensorflow.KernelDef.AttrConstraint}
     */
    public  static final class AttrConstraint extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:tensorflow.KernelDef.AttrConstraint)
        AttrConstraintOrBuilder {
      // Use AttrConstraint.newBuilder() to construct.
      private AttrConstraint(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
      }
      private AttrConstraint() {
        name_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
      }
      private AttrConstraint(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
        this();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                String s = input.readStringRequireUtf8();

                name_ = s;
                break;
              }
              case 18: {
                tensorflow.AttrValueOuterClass.AttrValue.Builder subBuilder = null;
                if (allowedValues_ != null) {
                  subBuilder = allowedValues_.toBuilder();
                }
                allowedValues_ = input.readMessage(tensorflow.AttrValueOuterClass.AttrValue.parser(), extensionRegistry);
                if (subBuilder != null) {
                  subBuilder.mergeFrom(allowedValues_);
                  allowedValues_ = subBuilder.buildPartial();
                }

                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tensorflow.KernelDefOuterClass.internal_static_tensorflow_KernelDef_AttrConstraint_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tensorflow.KernelDefOuterClass.internal_static_tensorflow_KernelDef_AttrConstraint_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint.class, tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint.Builder.class);
      }

      public static final int NAME_FIELD_NUMBER = 1;
      private volatile java.lang.Object name_;
      /**
       * <code>optional string name = 1;</code>
       *
       * <pre>
       * Name of an attr from the Op.
       * </pre>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       *
       * <pre>
       * Name of an attr from the Op.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int ALLOWED_VALUES_FIELD_NUMBER = 2;
      private tensorflow.AttrValueOuterClass.AttrValue allowedValues_;
      /**
       * <code>optional .tensorflow.AttrValue allowed_values = 2;</code>
       *
       * <pre>
       * A list of values that this kernel supports for this attr.
       * Like OpDef.AttrDef.allowed_values, except for kernels instead of Ops.
       * </pre>
       */
      public boolean hasAllowedValues() {
        return allowedValues_ != null;
      }
      /**
       * <code>optional .tensorflow.AttrValue allowed_values = 2;</code>
       *
       * <pre>
       * A list of values that this kernel supports for this attr.
       * Like OpDef.AttrDef.allowed_values, except for kernels instead of Ops.
       * </pre>
       */
      public tensorflow.AttrValueOuterClass.AttrValue getAllowedValues() {
        return allowedValues_ == null ? tensorflow.AttrValueOuterClass.AttrValue.getDefaultInstance() : allowedValues_;
      }
      /**
       * <code>optional .tensorflow.AttrValue allowed_values = 2;</code>
       *
       * <pre>
       * A list of values that this kernel supports for this attr.
       * Like OpDef.AttrDef.allowed_values, except for kernels instead of Ops.
       * </pre>
       */
      public tensorflow.AttrValueOuterClass.AttrValueOrBuilder getAllowedValuesOrBuilder() {
        return getAllowedValues();
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getNameBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
        }
        if (allowedValues_ != null) {
          output.writeMessage(2, getAllowedValues());
        }
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getNameBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
        }
        if (allowedValues_ != null) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, getAllowedValues());
        }
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      public static tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code tensorflow.KernelDef.AttrConstraint}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:tensorflow.KernelDef.AttrConstraint)
          tensorflow.KernelDefOuterClass.KernelDef.AttrConstraintOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return tensorflow.KernelDefOuterClass.internal_static_tensorflow_KernelDef_AttrConstraint_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return tensorflow.KernelDefOuterClass.internal_static_tensorflow_KernelDef_AttrConstraint_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint.class, tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint.Builder.class);
        }

        // Construct using tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          name_ = "";

          if (allowedValuesBuilder_ == null) {
            allowedValues_ = null;
          } else {
            allowedValues_ = null;
            allowedValuesBuilder_ = null;
          }
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return tensorflow.KernelDefOuterClass.internal_static_tensorflow_KernelDef_AttrConstraint_descriptor;
        }

        public tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint getDefaultInstanceForType() {
          return tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint.getDefaultInstance();
        }

        public tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint build() {
          tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint buildPartial() {
          tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint result = new tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint(this);
          result.name_ = name_;
          if (allowedValuesBuilder_ == null) {
            result.allowedValues_ = allowedValues_;
          } else {
            result.allowedValues_ = allowedValuesBuilder_.build();
          }
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint) {
            return mergeFrom((tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint other) {
          if (other == tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint.getDefaultInstance()) return this;
          if (!other.getName().isEmpty()) {
            name_ = other.name_;
            onChanged();
          }
          if (other.hasAllowedValues()) {
            mergeAllowedValues(other.getAllowedValues());
          }
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object name_ = "";
        /**
         * <code>optional string name = 1;</code>
         *
         * <pre>
         * Name of an attr from the Op.
         * </pre>
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string name = 1;</code>
         *
         * <pre>
         * Name of an attr from the Op.
         * </pre>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string name = 1;</code>
         *
         * <pre>
         * Name of an attr from the Op.
         * </pre>
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string name = 1;</code>
         *
         * <pre>
         * Name of an attr from the Op.
         * </pre>
         */
        public Builder clearName() {
          
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>optional string name = 1;</code>
         *
         * <pre>
         * Name of an attr from the Op.
         * </pre>
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          name_ = value;
          onChanged();
          return this;
        }

        private tensorflow.AttrValueOuterClass.AttrValue allowedValues_ = null;
        private com.google.protobuf.SingleFieldBuilder<
            tensorflow.AttrValueOuterClass.AttrValue, tensorflow.AttrValueOuterClass.AttrValue.Builder, tensorflow.AttrValueOuterClass.AttrValueOrBuilder> allowedValuesBuilder_;
        /**
         * <code>optional .tensorflow.AttrValue allowed_values = 2;</code>
         *
         * <pre>
         * A list of values that this kernel supports for this attr.
         * Like OpDef.AttrDef.allowed_values, except for kernels instead of Ops.
         * </pre>
         */
        public boolean hasAllowedValues() {
          return allowedValuesBuilder_ != null || allowedValues_ != null;
        }
        /**
         * <code>optional .tensorflow.AttrValue allowed_values = 2;</code>
         *
         * <pre>
         * A list of values that this kernel supports for this attr.
         * Like OpDef.AttrDef.allowed_values, except for kernels instead of Ops.
         * </pre>
         */
        public tensorflow.AttrValueOuterClass.AttrValue getAllowedValues() {
          if (allowedValuesBuilder_ == null) {
            return allowedValues_ == null ? tensorflow.AttrValueOuterClass.AttrValue.getDefaultInstance() : allowedValues_;
          } else {
            return allowedValuesBuilder_.getMessage();
          }
        }
        /**
         * <code>optional .tensorflow.AttrValue allowed_values = 2;</code>
         *
         * <pre>
         * A list of values that this kernel supports for this attr.
         * Like OpDef.AttrDef.allowed_values, except for kernels instead of Ops.
         * </pre>
         */
        public Builder setAllowedValues(tensorflow.AttrValueOuterClass.AttrValue value) {
          if (allowedValuesBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            allowedValues_ = value;
            onChanged();
          } else {
            allowedValuesBuilder_.setMessage(value);
          }

          return this;
        }
        /**
         * <code>optional .tensorflow.AttrValue allowed_values = 2;</code>
         *
         * <pre>
         * A list of values that this kernel supports for this attr.
         * Like OpDef.AttrDef.allowed_values, except for kernels instead of Ops.
         * </pre>
         */
        public Builder setAllowedValues(
            tensorflow.AttrValueOuterClass.AttrValue.Builder builderForValue) {
          if (allowedValuesBuilder_ == null) {
            allowedValues_ = builderForValue.build();
            onChanged();
          } else {
            allowedValuesBuilder_.setMessage(builderForValue.build());
          }

          return this;
        }
        /**
         * <code>optional .tensorflow.AttrValue allowed_values = 2;</code>
         *
         * <pre>
         * A list of values that this kernel supports for this attr.
         * Like OpDef.AttrDef.allowed_values, except for kernels instead of Ops.
         * </pre>
         */
        public Builder mergeAllowedValues(tensorflow.AttrValueOuterClass.AttrValue value) {
          if (allowedValuesBuilder_ == null) {
            if (allowedValues_ != null) {
              allowedValues_ =
                tensorflow.AttrValueOuterClass.AttrValue.newBuilder(allowedValues_).mergeFrom(value).buildPartial();
            } else {
              allowedValues_ = value;
            }
            onChanged();
          } else {
            allowedValuesBuilder_.mergeFrom(value);
          }

          return this;
        }
        /**
         * <code>optional .tensorflow.AttrValue allowed_values = 2;</code>
         *
         * <pre>
         * A list of values that this kernel supports for this attr.
         * Like OpDef.AttrDef.allowed_values, except for kernels instead of Ops.
         * </pre>
         */
        public Builder clearAllowedValues() {
          if (allowedValuesBuilder_ == null) {
            allowedValues_ = null;
            onChanged();
          } else {
            allowedValues_ = null;
            allowedValuesBuilder_ = null;
          }

          return this;
        }
        /**
         * <code>optional .tensorflow.AttrValue allowed_values = 2;</code>
         *
         * <pre>
         * A list of values that this kernel supports for this attr.
         * Like OpDef.AttrDef.allowed_values, except for kernels instead of Ops.
         * </pre>
         */
        public tensorflow.AttrValueOuterClass.AttrValue.Builder getAllowedValuesBuilder() {
          
          onChanged();
          return getAllowedValuesFieldBuilder().getBuilder();
        }
        /**
         * <code>optional .tensorflow.AttrValue allowed_values = 2;</code>
         *
         * <pre>
         * A list of values that this kernel supports for this attr.
         * Like OpDef.AttrDef.allowed_values, except for kernels instead of Ops.
         * </pre>
         */
        public tensorflow.AttrValueOuterClass.AttrValueOrBuilder getAllowedValuesOrBuilder() {
          if (allowedValuesBuilder_ != null) {
            return allowedValuesBuilder_.getMessageOrBuilder();
          } else {
            return allowedValues_ == null ?
                tensorflow.AttrValueOuterClass.AttrValue.getDefaultInstance() : allowedValues_;
          }
        }
        /**
         * <code>optional .tensorflow.AttrValue allowed_values = 2;</code>
         *
         * <pre>
         * A list of values that this kernel supports for this attr.
         * Like OpDef.AttrDef.allowed_values, except for kernels instead of Ops.
         * </pre>
         */
        private com.google.protobuf.SingleFieldBuilder<
            tensorflow.AttrValueOuterClass.AttrValue, tensorflow.AttrValueOuterClass.AttrValue.Builder, tensorflow.AttrValueOuterClass.AttrValueOrBuilder> 
            getAllowedValuesFieldBuilder() {
          if (allowedValuesBuilder_ == null) {
            allowedValuesBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                tensorflow.AttrValueOuterClass.AttrValue, tensorflow.AttrValueOuterClass.AttrValue.Builder, tensorflow.AttrValueOuterClass.AttrValueOrBuilder>(
                    getAllowedValues(),
                    getParentForChildren(),
                    isClean());
            allowedValues_ = null;
          }
          return allowedValuesBuilder_;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }


        // @@protoc_insertion_point(builder_scope:tensorflow.KernelDef.AttrConstraint)
      }

      // @@protoc_insertion_point(class_scope:tensorflow.KernelDef.AttrConstraint)
      private static final tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint();
      }

      public static tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<AttrConstraint>
          PARSER = new com.google.protobuf.AbstractParser<AttrConstraint>() {
        public AttrConstraint parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          try {
            return new AttrConstraint(input, extensionRegistry);
          } catch (RuntimeException e) {
            if (e.getCause() instanceof
                com.google.protobuf.InvalidProtocolBufferException) {
              throw (com.google.protobuf.InvalidProtocolBufferException)
                  e.getCause();
            }
            throw e;
          }
        }
      };

      public static com.google.protobuf.Parser<AttrConstraint> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<AttrConstraint> getParserForType() {
        return PARSER;
      }

      public tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int OP_FIELD_NUMBER = 1;
    private volatile java.lang.Object op_;
    /**
     * <code>optional string op = 1;</code>
     *
     * <pre>
     * Must match the name of an Op.
     * </pre>
     */
    public java.lang.String getOp() {
      java.lang.Object ref = op_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        op_ = s;
        return s;
      }
    }
    /**
     * <code>optional string op = 1;</code>
     *
     * <pre>
     * Must match the name of an Op.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getOpBytes() {
      java.lang.Object ref = op_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        op_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICE_TYPE_FIELD_NUMBER = 2;
    private volatile java.lang.Object deviceType_;
    /**
     * <code>optional string device_type = 2;</code>
     *
     * <pre>
     * Type of device this kernel runs on.
     * </pre>
     */
    public java.lang.String getDeviceType() {
      java.lang.Object ref = deviceType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceType_ = s;
        return s;
      }
    }
    /**
     * <code>optional string device_type = 2;</code>
     *
     * <pre>
     * Type of device this kernel runs on.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getDeviceTypeBytes() {
      java.lang.Object ref = deviceType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONSTRAINT_FIELD_NUMBER = 3;
    private java.util.List<tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint> constraint_;
    /**
     * <code>repeated .tensorflow.KernelDef.AttrConstraint constraint = 3;</code>
     */
    public java.util.List<tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint> getConstraintList() {
      return constraint_;
    }
    /**
     * <code>repeated .tensorflow.KernelDef.AttrConstraint constraint = 3;</code>
     */
    public java.util.List<? extends tensorflow.KernelDefOuterClass.KernelDef.AttrConstraintOrBuilder> 
        getConstraintOrBuilderList() {
      return constraint_;
    }
    /**
     * <code>repeated .tensorflow.KernelDef.AttrConstraint constraint = 3;</code>
     */
    public int getConstraintCount() {
      return constraint_.size();
    }
    /**
     * <code>repeated .tensorflow.KernelDef.AttrConstraint constraint = 3;</code>
     */
    public tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint getConstraint(int index) {
      return constraint_.get(index);
    }
    /**
     * <code>repeated .tensorflow.KernelDef.AttrConstraint constraint = 3;</code>
     */
    public tensorflow.KernelDefOuterClass.KernelDef.AttrConstraintOrBuilder getConstraintOrBuilder(
        int index) {
      return constraint_.get(index);
    }

    public static final int HOST_MEMORY_ARG_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList hostMemoryArg_;
    /**
     * <code>repeated string host_memory_arg = 4;</code>
     *
     * <pre>
     * Names of the Op's input_/output_args that reside in host memory
     * instead of device memory.
     * </pre>
     */
    public com.google.protobuf.ProtocolStringList
        getHostMemoryArgList() {
      return hostMemoryArg_;
    }
    /**
     * <code>repeated string host_memory_arg = 4;</code>
     *
     * <pre>
     * Names of the Op's input_/output_args that reside in host memory
     * instead of device memory.
     * </pre>
     */
    public int getHostMemoryArgCount() {
      return hostMemoryArg_.size();
    }
    /**
     * <code>repeated string host_memory_arg = 4;</code>
     *
     * <pre>
     * Names of the Op's input_/output_args that reside in host memory
     * instead of device memory.
     * </pre>
     */
    public java.lang.String getHostMemoryArg(int index) {
      return hostMemoryArg_.get(index);
    }
    /**
     * <code>repeated string host_memory_arg = 4;</code>
     *
     * <pre>
     * Names of the Op's input_/output_args that reside in host memory
     * instead of device memory.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getHostMemoryArgBytes(int index) {
      return hostMemoryArg_.getByteString(index);
    }

    public static final int LABEL_FIELD_NUMBER = 5;
    private volatile java.lang.Object label_;
    /**
     * <code>optional string label = 5;</code>
     *
     * <pre>
     * This allows experimental kernels to be registered for an op that
     * won't be used unless the user specifies a "_kernel" attr with
     * value matching this.
     * </pre>
     */
    public java.lang.String getLabel() {
      java.lang.Object ref = label_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        label_ = s;
        return s;
      }
    }
    /**
     * <code>optional string label = 5;</code>
     *
     * <pre>
     * This allows experimental kernels to be registered for an op that
     * won't be used unless the user specifies a "_kernel" attr with
     * value matching this.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getLabelBytes() {
      java.lang.Object ref = label_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        label_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getOpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, op_);
      }
      if (!getDeviceTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, deviceType_);
      }
      for (int i = 0; i < constraint_.size(); i++) {
        output.writeMessage(3, constraint_.get(i));
      }
      for (int i = 0; i < hostMemoryArg_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, hostMemoryArg_.getRaw(i));
      }
      if (!getLabelBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, label_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getOpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, op_);
      }
      if (!getDeviceTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, deviceType_);
      }
      for (int i = 0; i < constraint_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, constraint_.get(i));
      }
      {
        int dataSize = 0;
        for (int i = 0; i < hostMemoryArg_.size(); i++) {
          dataSize += computeStringSizeNoTag(hostMemoryArg_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getHostMemoryArgList().size();
      }
      if (!getLabelBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(5, label_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static tensorflow.KernelDefOuterClass.KernelDef parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tensorflow.KernelDefOuterClass.KernelDef parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tensorflow.KernelDefOuterClass.KernelDef parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tensorflow.KernelDefOuterClass.KernelDef parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tensorflow.KernelDefOuterClass.KernelDef parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static tensorflow.KernelDefOuterClass.KernelDef parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static tensorflow.KernelDefOuterClass.KernelDef parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static tensorflow.KernelDefOuterClass.KernelDef parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static tensorflow.KernelDefOuterClass.KernelDef parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static tensorflow.KernelDefOuterClass.KernelDef parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(tensorflow.KernelDefOuterClass.KernelDef prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tensorflow.KernelDef}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tensorflow.KernelDef)
        tensorflow.KernelDefOuterClass.KernelDefOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tensorflow.KernelDefOuterClass.internal_static_tensorflow_KernelDef_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tensorflow.KernelDefOuterClass.internal_static_tensorflow_KernelDef_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tensorflow.KernelDefOuterClass.KernelDef.class, tensorflow.KernelDefOuterClass.KernelDef.Builder.class);
      }

      // Construct using tensorflow.KernelDefOuterClass.KernelDef.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getConstraintFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        op_ = "";

        deviceType_ = "";

        if (constraintBuilder_ == null) {
          constraint_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          constraintBuilder_.clear();
        }
        hostMemoryArg_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        label_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tensorflow.KernelDefOuterClass.internal_static_tensorflow_KernelDef_descriptor;
      }

      public tensorflow.KernelDefOuterClass.KernelDef getDefaultInstanceForType() {
        return tensorflow.KernelDefOuterClass.KernelDef.getDefaultInstance();
      }

      public tensorflow.KernelDefOuterClass.KernelDef build() {
        tensorflow.KernelDefOuterClass.KernelDef result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public tensorflow.KernelDefOuterClass.KernelDef buildPartial() {
        tensorflow.KernelDefOuterClass.KernelDef result = new tensorflow.KernelDefOuterClass.KernelDef(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.op_ = op_;
        result.deviceType_ = deviceType_;
        if (constraintBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            constraint_ = java.util.Collections.unmodifiableList(constraint_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.constraint_ = constraint_;
        } else {
          result.constraint_ = constraintBuilder_.build();
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          hostMemoryArg_ = hostMemoryArg_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.hostMemoryArg_ = hostMemoryArg_;
        result.label_ = label_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tensorflow.KernelDefOuterClass.KernelDef) {
          return mergeFrom((tensorflow.KernelDefOuterClass.KernelDef)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tensorflow.KernelDefOuterClass.KernelDef other) {
        if (other == tensorflow.KernelDefOuterClass.KernelDef.getDefaultInstance()) return this;
        if (!other.getOp().isEmpty()) {
          op_ = other.op_;
          onChanged();
        }
        if (!other.getDeviceType().isEmpty()) {
          deviceType_ = other.deviceType_;
          onChanged();
        }
        if (constraintBuilder_ == null) {
          if (!other.constraint_.isEmpty()) {
            if (constraint_.isEmpty()) {
              constraint_ = other.constraint_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureConstraintIsMutable();
              constraint_.addAll(other.constraint_);
            }
            onChanged();
          }
        } else {
          if (!other.constraint_.isEmpty()) {
            if (constraintBuilder_.isEmpty()) {
              constraintBuilder_.dispose();
              constraintBuilder_ = null;
              constraint_ = other.constraint_;
              bitField0_ = (bitField0_ & ~0x00000004);
              constraintBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getConstraintFieldBuilder() : null;
            } else {
              constraintBuilder_.addAllMessages(other.constraint_);
            }
          }
        }
        if (!other.hostMemoryArg_.isEmpty()) {
          if (hostMemoryArg_.isEmpty()) {
            hostMemoryArg_ = other.hostMemoryArg_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureHostMemoryArgIsMutable();
            hostMemoryArg_.addAll(other.hostMemoryArg_);
          }
          onChanged();
        }
        if (!other.getLabel().isEmpty()) {
          label_ = other.label_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        tensorflow.KernelDefOuterClass.KernelDef parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (tensorflow.KernelDefOuterClass.KernelDef) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object op_ = "";
      /**
       * <code>optional string op = 1;</code>
       *
       * <pre>
       * Must match the name of an Op.
       * </pre>
       */
      public java.lang.String getOp() {
        java.lang.Object ref = op_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          op_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string op = 1;</code>
       *
       * <pre>
       * Must match the name of an Op.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getOpBytes() {
        java.lang.Object ref = op_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          op_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string op = 1;</code>
       *
       * <pre>
       * Must match the name of an Op.
       * </pre>
       */
      public Builder setOp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        op_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string op = 1;</code>
       *
       * <pre>
       * Must match the name of an Op.
       * </pre>
       */
      public Builder clearOp() {
        
        op_ = getDefaultInstance().getOp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string op = 1;</code>
       *
       * <pre>
       * Must match the name of an Op.
       * </pre>
       */
      public Builder setOpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        op_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object deviceType_ = "";
      /**
       * <code>optional string device_type = 2;</code>
       *
       * <pre>
       * Type of device this kernel runs on.
       * </pre>
       */
      public java.lang.String getDeviceType() {
        java.lang.Object ref = deviceType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          deviceType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string device_type = 2;</code>
       *
       * <pre>
       * Type of device this kernel runs on.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getDeviceTypeBytes() {
        java.lang.Object ref = deviceType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string device_type = 2;</code>
       *
       * <pre>
       * Type of device this kernel runs on.
       * </pre>
       */
      public Builder setDeviceType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string device_type = 2;</code>
       *
       * <pre>
       * Type of device this kernel runs on.
       * </pre>
       */
      public Builder clearDeviceType() {
        
        deviceType_ = getDefaultInstance().getDeviceType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string device_type = 2;</code>
       *
       * <pre>
       * Type of device this kernel runs on.
       * </pre>
       */
      public Builder setDeviceTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deviceType_ = value;
        onChanged();
        return this;
      }

      private java.util.List<tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint> constraint_ =
        java.util.Collections.emptyList();
      private void ensureConstraintIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          constraint_ = new java.util.ArrayList<tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint>(constraint_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint, tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint.Builder, tensorflow.KernelDefOuterClass.KernelDef.AttrConstraintOrBuilder> constraintBuilder_;

      /**
       * <code>repeated .tensorflow.KernelDef.AttrConstraint constraint = 3;</code>
       */
      public java.util.List<tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint> getConstraintList() {
        if (constraintBuilder_ == null) {
          return java.util.Collections.unmodifiableList(constraint_);
        } else {
          return constraintBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .tensorflow.KernelDef.AttrConstraint constraint = 3;</code>
       */
      public int getConstraintCount() {
        if (constraintBuilder_ == null) {
          return constraint_.size();
        } else {
          return constraintBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .tensorflow.KernelDef.AttrConstraint constraint = 3;</code>
       */
      public tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint getConstraint(int index) {
        if (constraintBuilder_ == null) {
          return constraint_.get(index);
        } else {
          return constraintBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .tensorflow.KernelDef.AttrConstraint constraint = 3;</code>
       */
      public Builder setConstraint(
          int index, tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint value) {
        if (constraintBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConstraintIsMutable();
          constraint_.set(index, value);
          onChanged();
        } else {
          constraintBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tensorflow.KernelDef.AttrConstraint constraint = 3;</code>
       */
      public Builder setConstraint(
          int index, tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint.Builder builderForValue) {
        if (constraintBuilder_ == null) {
          ensureConstraintIsMutable();
          constraint_.set(index, builderForValue.build());
          onChanged();
        } else {
          constraintBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tensorflow.KernelDef.AttrConstraint constraint = 3;</code>
       */
      public Builder addConstraint(tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint value) {
        if (constraintBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConstraintIsMutable();
          constraint_.add(value);
          onChanged();
        } else {
          constraintBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .tensorflow.KernelDef.AttrConstraint constraint = 3;</code>
       */
      public Builder addConstraint(
          int index, tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint value) {
        if (constraintBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConstraintIsMutable();
          constraint_.add(index, value);
          onChanged();
        } else {
          constraintBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .tensorflow.KernelDef.AttrConstraint constraint = 3;</code>
       */
      public Builder addConstraint(
          tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint.Builder builderForValue) {
        if (constraintBuilder_ == null) {
          ensureConstraintIsMutable();
          constraint_.add(builderForValue.build());
          onChanged();
        } else {
          constraintBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tensorflow.KernelDef.AttrConstraint constraint = 3;</code>
       */
      public Builder addConstraint(
          int index, tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint.Builder builderForValue) {
        if (constraintBuilder_ == null) {
          ensureConstraintIsMutable();
          constraint_.add(index, builderForValue.build());
          onChanged();
        } else {
          constraintBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .tensorflow.KernelDef.AttrConstraint constraint = 3;</code>
       */
      public Builder addAllConstraint(
          java.lang.Iterable<? extends tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint> values) {
        if (constraintBuilder_ == null) {
          ensureConstraintIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, constraint_);
          onChanged();
        } else {
          constraintBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .tensorflow.KernelDef.AttrConstraint constraint = 3;</code>
       */
      public Builder clearConstraint() {
        if (constraintBuilder_ == null) {
          constraint_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          constraintBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .tensorflow.KernelDef.AttrConstraint constraint = 3;</code>
       */
      public Builder removeConstraint(int index) {
        if (constraintBuilder_ == null) {
          ensureConstraintIsMutable();
          constraint_.remove(index);
          onChanged();
        } else {
          constraintBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .tensorflow.KernelDef.AttrConstraint constraint = 3;</code>
       */
      public tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint.Builder getConstraintBuilder(
          int index) {
        return getConstraintFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .tensorflow.KernelDef.AttrConstraint constraint = 3;</code>
       */
      public tensorflow.KernelDefOuterClass.KernelDef.AttrConstraintOrBuilder getConstraintOrBuilder(
          int index) {
        if (constraintBuilder_ == null) {
          return constraint_.get(index);  } else {
          return constraintBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .tensorflow.KernelDef.AttrConstraint constraint = 3;</code>
       */
      public java.util.List<? extends tensorflow.KernelDefOuterClass.KernelDef.AttrConstraintOrBuilder> 
           getConstraintOrBuilderList() {
        if (constraintBuilder_ != null) {
          return constraintBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(constraint_);
        }
      }
      /**
       * <code>repeated .tensorflow.KernelDef.AttrConstraint constraint = 3;</code>
       */
      public tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint.Builder addConstraintBuilder() {
        return getConstraintFieldBuilder().addBuilder(
            tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint.getDefaultInstance());
      }
      /**
       * <code>repeated .tensorflow.KernelDef.AttrConstraint constraint = 3;</code>
       */
      public tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint.Builder addConstraintBuilder(
          int index) {
        return getConstraintFieldBuilder().addBuilder(
            index, tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint.getDefaultInstance());
      }
      /**
       * <code>repeated .tensorflow.KernelDef.AttrConstraint constraint = 3;</code>
       */
      public java.util.List<tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint.Builder> 
           getConstraintBuilderList() {
        return getConstraintFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint, tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint.Builder, tensorflow.KernelDefOuterClass.KernelDef.AttrConstraintOrBuilder> 
          getConstraintFieldBuilder() {
        if (constraintBuilder_ == null) {
          constraintBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint, tensorflow.KernelDefOuterClass.KernelDef.AttrConstraint.Builder, tensorflow.KernelDefOuterClass.KernelDef.AttrConstraintOrBuilder>(
                  constraint_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          constraint_ = null;
        }
        return constraintBuilder_;
      }

      private com.google.protobuf.LazyStringList hostMemoryArg_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureHostMemoryArgIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          hostMemoryArg_ = new com.google.protobuf.LazyStringArrayList(hostMemoryArg_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string host_memory_arg = 4;</code>
       *
       * <pre>
       * Names of the Op's input_/output_args that reside in host memory
       * instead of device memory.
       * </pre>
       */
      public com.google.protobuf.ProtocolStringList
          getHostMemoryArgList() {
        return hostMemoryArg_.getUnmodifiableView();
      }
      /**
       * <code>repeated string host_memory_arg = 4;</code>
       *
       * <pre>
       * Names of the Op's input_/output_args that reside in host memory
       * instead of device memory.
       * </pre>
       */
      public int getHostMemoryArgCount() {
        return hostMemoryArg_.size();
      }
      /**
       * <code>repeated string host_memory_arg = 4;</code>
       *
       * <pre>
       * Names of the Op's input_/output_args that reside in host memory
       * instead of device memory.
       * </pre>
       */
      public java.lang.String getHostMemoryArg(int index) {
        return hostMemoryArg_.get(index);
      }
      /**
       * <code>repeated string host_memory_arg = 4;</code>
       *
       * <pre>
       * Names of the Op's input_/output_args that reside in host memory
       * instead of device memory.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getHostMemoryArgBytes(int index) {
        return hostMemoryArg_.getByteString(index);
      }
      /**
       * <code>repeated string host_memory_arg = 4;</code>
       *
       * <pre>
       * Names of the Op's input_/output_args that reside in host memory
       * instead of device memory.
       * </pre>
       */
      public Builder setHostMemoryArg(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureHostMemoryArgIsMutable();
        hostMemoryArg_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string host_memory_arg = 4;</code>
       *
       * <pre>
       * Names of the Op's input_/output_args that reside in host memory
       * instead of device memory.
       * </pre>
       */
      public Builder addHostMemoryArg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureHostMemoryArgIsMutable();
        hostMemoryArg_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string host_memory_arg = 4;</code>
       *
       * <pre>
       * Names of the Op's input_/output_args that reside in host memory
       * instead of device memory.
       * </pre>
       */
      public Builder addAllHostMemoryArg(
          java.lang.Iterable<java.lang.String> values) {
        ensureHostMemoryArgIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, hostMemoryArg_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string host_memory_arg = 4;</code>
       *
       * <pre>
       * Names of the Op's input_/output_args that reside in host memory
       * instead of device memory.
       * </pre>
       */
      public Builder clearHostMemoryArg() {
        hostMemoryArg_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string host_memory_arg = 4;</code>
       *
       * <pre>
       * Names of the Op's input_/output_args that reside in host memory
       * instead of device memory.
       * </pre>
       */
      public Builder addHostMemoryArgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureHostMemoryArgIsMutable();
        hostMemoryArg_.add(value);
        onChanged();
        return this;
      }

      private java.lang.Object label_ = "";
      /**
       * <code>optional string label = 5;</code>
       *
       * <pre>
       * This allows experimental kernels to be registered for an op that
       * won't be used unless the user specifies a "_kernel" attr with
       * value matching this.
       * </pre>
       */
      public java.lang.String getLabel() {
        java.lang.Object ref = label_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          label_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string label = 5;</code>
       *
       * <pre>
       * This allows experimental kernels to be registered for an op that
       * won't be used unless the user specifies a "_kernel" attr with
       * value matching this.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getLabelBytes() {
        java.lang.Object ref = label_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          label_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string label = 5;</code>
       *
       * <pre>
       * This allows experimental kernels to be registered for an op that
       * won't be used unless the user specifies a "_kernel" attr with
       * value matching this.
       * </pre>
       */
      public Builder setLabel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        label_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string label = 5;</code>
       *
       * <pre>
       * This allows experimental kernels to be registered for an op that
       * won't be used unless the user specifies a "_kernel" attr with
       * value matching this.
       * </pre>
       */
      public Builder clearLabel() {
        
        label_ = getDefaultInstance().getLabel();
        onChanged();
        return this;
      }
      /**
       * <code>optional string label = 5;</code>
       *
       * <pre>
       * This allows experimental kernels to be registered for an op that
       * won't be used unless the user specifies a "_kernel" attr with
       * value matching this.
       * </pre>
       */
      public Builder setLabelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        label_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:tensorflow.KernelDef)
    }

    // @@protoc_insertion_point(class_scope:tensorflow.KernelDef)
    private static final tensorflow.KernelDefOuterClass.KernelDef DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new tensorflow.KernelDefOuterClass.KernelDef();
    }

    public static tensorflow.KernelDefOuterClass.KernelDef getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<KernelDef>
        PARSER = new com.google.protobuf.AbstractParser<KernelDef>() {
      public KernelDef parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new KernelDef(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<KernelDef> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<KernelDef> getParserForType() {
      return PARSER;
    }

    public tensorflow.KernelDefOuterClass.KernelDef getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_KernelDef_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tensorflow_KernelDef_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_KernelDef_AttrConstraint_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tensorflow_KernelDef_AttrConstraint_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*tensorflow/core/framework/kernel_def.p" +
      "roto\022\ntensorflow\032*tensorflow/core/framew" +
      "ork/attr_value.proto\"\335\001\n\tKernelDef\022\n\n\002op" +
      "\030\001 \001(\t\022\023\n\013device_type\030\002 \001(\t\0228\n\nconstrain" +
      "t\030\003 \003(\0132$.tensorflow.KernelDef.AttrConst" +
      "raint\022\027\n\017host_memory_arg\030\004 \003(\t\022\r\n\005label\030" +
      "\005 \001(\t\032M\n\016AttrConstraint\022\014\n\004name\030\001 \001(\t\022-\n" +
      "\016allowed_values\030\002 \001(\0132\025.tensorflow.AttrV" +
      "alueb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          tensorflow.AttrValueOuterClass.getDescriptor(),
        }, assigner);
    internal_static_tensorflow_KernelDef_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tensorflow_KernelDef_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tensorflow_KernelDef_descriptor,
        new java.lang.String[] { "Op", "DeviceType", "Constraint", "HostMemoryArg", "Label", });
    internal_static_tensorflow_KernelDef_AttrConstraint_descriptor =
      internal_static_tensorflow_KernelDef_descriptor.getNestedTypes().get(0);
    internal_static_tensorflow_KernelDef_AttrConstraint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tensorflow_KernelDef_AttrConstraint_descriptor,
        new java.lang.String[] { "Name", "AllowedValues", });
    tensorflow.AttrValueOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
