// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/tensor_description.proto

package tensorflow;

public final class TensorDescriptionOuterClass {
  private TensorDescriptionOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TensorDescriptionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tensorflow.TensorDescription)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .tensorflow.DataType dtype = 1;</code>
     *
     * <pre>
     * Data type of tensor elements
     * </pre>
     */
    int getDtypeValue();
    /**
     * <code>optional .tensorflow.DataType dtype = 1;</code>
     *
     * <pre>
     * Data type of tensor elements
     * </pre>
     */
    tensorflow.Types.DataType getDtype();

    /**
     * <code>optional .tensorflow.TensorShapeProto shape = 2;</code>
     *
     * <pre>
     * Shape of the tensor.
     * </pre>
     */
    boolean hasShape();
    /**
     * <code>optional .tensorflow.TensorShapeProto shape = 2;</code>
     *
     * <pre>
     * Shape of the tensor.
     * </pre>
     */
    tensorflow.TensorShape.TensorShapeProto getShape();
    /**
     * <code>optional .tensorflow.TensorShapeProto shape = 2;</code>
     *
     * <pre>
     * Shape of the tensor.
     * </pre>
     */
    tensorflow.TensorShape.TensorShapeProtoOrBuilder getShapeOrBuilder();

    /**
     * <code>optional .tensorflow.AllocationDescription allocation_description = 4;</code>
     *
     * <pre>
     * Information about the size and allocator used for the data
     * </pre>
     */
    boolean hasAllocationDescription();
    /**
     * <code>optional .tensorflow.AllocationDescription allocation_description = 4;</code>
     *
     * <pre>
     * Information about the size and allocator used for the data
     * </pre>
     */
    tensorflow.AllocationDescriptionOuterClass.AllocationDescription getAllocationDescription();
    /**
     * <code>optional .tensorflow.AllocationDescription allocation_description = 4;</code>
     *
     * <pre>
     * Information about the size and allocator used for the data
     * </pre>
     */
    tensorflow.AllocationDescriptionOuterClass.AllocationDescriptionOrBuilder getAllocationDescriptionOrBuilder();
  }
  /**
   * Protobuf type {@code tensorflow.TensorDescription}
   */
  public  static final class TensorDescription extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:tensorflow.TensorDescription)
      TensorDescriptionOrBuilder {
    // Use TensorDescription.newBuilder() to construct.
    private TensorDescription(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private TensorDescription() {
      dtype_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private TensorDescription(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              dtype_ = rawValue;
              break;
            }
            case 18: {
              tensorflow.TensorShape.TensorShapeProto.Builder subBuilder = null;
              if (shape_ != null) {
                subBuilder = shape_.toBuilder();
              }
              shape_ = input.readMessage(tensorflow.TensorShape.TensorShapeProto.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(shape_);
                shape_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              tensorflow.AllocationDescriptionOuterClass.AllocationDescription.Builder subBuilder = null;
              if (allocationDescription_ != null) {
                subBuilder = allocationDescription_.toBuilder();
              }
              allocationDescription_ = input.readMessage(tensorflow.AllocationDescriptionOuterClass.AllocationDescription.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(allocationDescription_);
                allocationDescription_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tensorflow.TensorDescriptionOuterClass.internal_static_tensorflow_TensorDescription_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tensorflow.TensorDescriptionOuterClass.internal_static_tensorflow_TensorDescription_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tensorflow.TensorDescriptionOuterClass.TensorDescription.class, tensorflow.TensorDescriptionOuterClass.TensorDescription.Builder.class);
    }

    public static final int DTYPE_FIELD_NUMBER = 1;
    private int dtype_;
    /**
     * <code>optional .tensorflow.DataType dtype = 1;</code>
     *
     * <pre>
     * Data type of tensor elements
     * </pre>
     */
    public int getDtypeValue() {
      return dtype_;
    }
    /**
     * <code>optional .tensorflow.DataType dtype = 1;</code>
     *
     * <pre>
     * Data type of tensor elements
     * </pre>
     */
    public tensorflow.Types.DataType getDtype() {
      tensorflow.Types.DataType result = tensorflow.Types.DataType.valueOf(dtype_);
      return result == null ? tensorflow.Types.DataType.UNRECOGNIZED : result;
    }

    public static final int SHAPE_FIELD_NUMBER = 2;
    private tensorflow.TensorShape.TensorShapeProto shape_;
    /**
     * <code>optional .tensorflow.TensorShapeProto shape = 2;</code>
     *
     * <pre>
     * Shape of the tensor.
     * </pre>
     */
    public boolean hasShape() {
      return shape_ != null;
    }
    /**
     * <code>optional .tensorflow.TensorShapeProto shape = 2;</code>
     *
     * <pre>
     * Shape of the tensor.
     * </pre>
     */
    public tensorflow.TensorShape.TensorShapeProto getShape() {
      return shape_ == null ? tensorflow.TensorShape.TensorShapeProto.getDefaultInstance() : shape_;
    }
    /**
     * <code>optional .tensorflow.TensorShapeProto shape = 2;</code>
     *
     * <pre>
     * Shape of the tensor.
     * </pre>
     */
    public tensorflow.TensorShape.TensorShapeProtoOrBuilder getShapeOrBuilder() {
      return getShape();
    }

    public static final int ALLOCATION_DESCRIPTION_FIELD_NUMBER = 4;
    private tensorflow.AllocationDescriptionOuterClass.AllocationDescription allocationDescription_;
    /**
     * <code>optional .tensorflow.AllocationDescription allocation_description = 4;</code>
     *
     * <pre>
     * Information about the size and allocator used for the data
     * </pre>
     */
    public boolean hasAllocationDescription() {
      return allocationDescription_ != null;
    }
    /**
     * <code>optional .tensorflow.AllocationDescription allocation_description = 4;</code>
     *
     * <pre>
     * Information about the size and allocator used for the data
     * </pre>
     */
    public tensorflow.AllocationDescriptionOuterClass.AllocationDescription getAllocationDescription() {
      return allocationDescription_ == null ? tensorflow.AllocationDescriptionOuterClass.AllocationDescription.getDefaultInstance() : allocationDescription_;
    }
    /**
     * <code>optional .tensorflow.AllocationDescription allocation_description = 4;</code>
     *
     * <pre>
     * Information about the size and allocator used for the data
     * </pre>
     */
    public tensorflow.AllocationDescriptionOuterClass.AllocationDescriptionOrBuilder getAllocationDescriptionOrBuilder() {
      return getAllocationDescription();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (dtype_ != tensorflow.Types.DataType.DT_INVALID.getNumber()) {
        output.writeEnum(1, dtype_);
      }
      if (shape_ != null) {
        output.writeMessage(2, getShape());
      }
      if (allocationDescription_ != null) {
        output.writeMessage(4, getAllocationDescription());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (dtype_ != tensorflow.Types.DataType.DT_INVALID.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, dtype_);
      }
      if (shape_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getShape());
      }
      if (allocationDescription_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getAllocationDescription());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static tensorflow.TensorDescriptionOuterClass.TensorDescription parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tensorflow.TensorDescriptionOuterClass.TensorDescription parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tensorflow.TensorDescriptionOuterClass.TensorDescription parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tensorflow.TensorDescriptionOuterClass.TensorDescription parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tensorflow.TensorDescriptionOuterClass.TensorDescription parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static tensorflow.TensorDescriptionOuterClass.TensorDescription parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static tensorflow.TensorDescriptionOuterClass.TensorDescription parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static tensorflow.TensorDescriptionOuterClass.TensorDescription parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static tensorflow.TensorDescriptionOuterClass.TensorDescription parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static tensorflow.TensorDescriptionOuterClass.TensorDescription parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(tensorflow.TensorDescriptionOuterClass.TensorDescription prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tensorflow.TensorDescription}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tensorflow.TensorDescription)
        tensorflow.TensorDescriptionOuterClass.TensorDescriptionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tensorflow.TensorDescriptionOuterClass.internal_static_tensorflow_TensorDescription_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tensorflow.TensorDescriptionOuterClass.internal_static_tensorflow_TensorDescription_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tensorflow.TensorDescriptionOuterClass.TensorDescription.class, tensorflow.TensorDescriptionOuterClass.TensorDescription.Builder.class);
      }

      // Construct using tensorflow.TensorDescriptionOuterClass.TensorDescription.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        dtype_ = 0;

        if (shapeBuilder_ == null) {
          shape_ = null;
        } else {
          shape_ = null;
          shapeBuilder_ = null;
        }
        if (allocationDescriptionBuilder_ == null) {
          allocationDescription_ = null;
        } else {
          allocationDescription_ = null;
          allocationDescriptionBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tensorflow.TensorDescriptionOuterClass.internal_static_tensorflow_TensorDescription_descriptor;
      }

      public tensorflow.TensorDescriptionOuterClass.TensorDescription getDefaultInstanceForType() {
        return tensorflow.TensorDescriptionOuterClass.TensorDescription.getDefaultInstance();
      }

      public tensorflow.TensorDescriptionOuterClass.TensorDescription build() {
        tensorflow.TensorDescriptionOuterClass.TensorDescription result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public tensorflow.TensorDescriptionOuterClass.TensorDescription buildPartial() {
        tensorflow.TensorDescriptionOuterClass.TensorDescription result = new tensorflow.TensorDescriptionOuterClass.TensorDescription(this);
        result.dtype_ = dtype_;
        if (shapeBuilder_ == null) {
          result.shape_ = shape_;
        } else {
          result.shape_ = shapeBuilder_.build();
        }
        if (allocationDescriptionBuilder_ == null) {
          result.allocationDescription_ = allocationDescription_;
        } else {
          result.allocationDescription_ = allocationDescriptionBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tensorflow.TensorDescriptionOuterClass.TensorDescription) {
          return mergeFrom((tensorflow.TensorDescriptionOuterClass.TensorDescription)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tensorflow.TensorDescriptionOuterClass.TensorDescription other) {
        if (other == tensorflow.TensorDescriptionOuterClass.TensorDescription.getDefaultInstance()) return this;
        if (other.dtype_ != 0) {
          setDtypeValue(other.getDtypeValue());
        }
        if (other.hasShape()) {
          mergeShape(other.getShape());
        }
        if (other.hasAllocationDescription()) {
          mergeAllocationDescription(other.getAllocationDescription());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        tensorflow.TensorDescriptionOuterClass.TensorDescription parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (tensorflow.TensorDescriptionOuterClass.TensorDescription) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int dtype_ = 0;
      /**
       * <code>optional .tensorflow.DataType dtype = 1;</code>
       *
       * <pre>
       * Data type of tensor elements
       * </pre>
       */
      public int getDtypeValue() {
        return dtype_;
      }
      /**
       * <code>optional .tensorflow.DataType dtype = 1;</code>
       *
       * <pre>
       * Data type of tensor elements
       * </pre>
       */
      public Builder setDtypeValue(int value) {
        dtype_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .tensorflow.DataType dtype = 1;</code>
       *
       * <pre>
       * Data type of tensor elements
       * </pre>
       */
      public tensorflow.Types.DataType getDtype() {
        tensorflow.Types.DataType result = tensorflow.Types.DataType.valueOf(dtype_);
        return result == null ? tensorflow.Types.DataType.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .tensorflow.DataType dtype = 1;</code>
       *
       * <pre>
       * Data type of tensor elements
       * </pre>
       */
      public Builder setDtype(tensorflow.Types.DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        dtype_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .tensorflow.DataType dtype = 1;</code>
       *
       * <pre>
       * Data type of tensor elements
       * </pre>
       */
      public Builder clearDtype() {
        
        dtype_ = 0;
        onChanged();
        return this;
      }

      private tensorflow.TensorShape.TensorShapeProto shape_ = null;
      private com.google.protobuf.SingleFieldBuilder<
          tensorflow.TensorShape.TensorShapeProto, tensorflow.TensorShape.TensorShapeProto.Builder, tensorflow.TensorShape.TensorShapeProtoOrBuilder> shapeBuilder_;
      /**
       * <code>optional .tensorflow.TensorShapeProto shape = 2;</code>
       *
       * <pre>
       * Shape of the tensor.
       * </pre>
       */
      public boolean hasShape() {
        return shapeBuilder_ != null || shape_ != null;
      }
      /**
       * <code>optional .tensorflow.TensorShapeProto shape = 2;</code>
       *
       * <pre>
       * Shape of the tensor.
       * </pre>
       */
      public tensorflow.TensorShape.TensorShapeProto getShape() {
        if (shapeBuilder_ == null) {
          return shape_ == null ? tensorflow.TensorShape.TensorShapeProto.getDefaultInstance() : shape_;
        } else {
          return shapeBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .tensorflow.TensorShapeProto shape = 2;</code>
       *
       * <pre>
       * Shape of the tensor.
       * </pre>
       */
      public Builder setShape(tensorflow.TensorShape.TensorShapeProto value) {
        if (shapeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          shape_ = value;
          onChanged();
        } else {
          shapeBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .tensorflow.TensorShapeProto shape = 2;</code>
       *
       * <pre>
       * Shape of the tensor.
       * </pre>
       */
      public Builder setShape(
          tensorflow.TensorShape.TensorShapeProto.Builder builderForValue) {
        if (shapeBuilder_ == null) {
          shape_ = builderForValue.build();
          onChanged();
        } else {
          shapeBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .tensorflow.TensorShapeProto shape = 2;</code>
       *
       * <pre>
       * Shape of the tensor.
       * </pre>
       */
      public Builder mergeShape(tensorflow.TensorShape.TensorShapeProto value) {
        if (shapeBuilder_ == null) {
          if (shape_ != null) {
            shape_ =
              tensorflow.TensorShape.TensorShapeProto.newBuilder(shape_).mergeFrom(value).buildPartial();
          } else {
            shape_ = value;
          }
          onChanged();
        } else {
          shapeBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .tensorflow.TensorShapeProto shape = 2;</code>
       *
       * <pre>
       * Shape of the tensor.
       * </pre>
       */
      public Builder clearShape() {
        if (shapeBuilder_ == null) {
          shape_ = null;
          onChanged();
        } else {
          shape_ = null;
          shapeBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .tensorflow.TensorShapeProto shape = 2;</code>
       *
       * <pre>
       * Shape of the tensor.
       * </pre>
       */
      public tensorflow.TensorShape.TensorShapeProto.Builder getShapeBuilder() {
        
        onChanged();
        return getShapeFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .tensorflow.TensorShapeProto shape = 2;</code>
       *
       * <pre>
       * Shape of the tensor.
       * </pre>
       */
      public tensorflow.TensorShape.TensorShapeProtoOrBuilder getShapeOrBuilder() {
        if (shapeBuilder_ != null) {
          return shapeBuilder_.getMessageOrBuilder();
        } else {
          return shape_ == null ?
              tensorflow.TensorShape.TensorShapeProto.getDefaultInstance() : shape_;
        }
      }
      /**
       * <code>optional .tensorflow.TensorShapeProto shape = 2;</code>
       *
       * <pre>
       * Shape of the tensor.
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          tensorflow.TensorShape.TensorShapeProto, tensorflow.TensorShape.TensorShapeProto.Builder, tensorflow.TensorShape.TensorShapeProtoOrBuilder> 
          getShapeFieldBuilder() {
        if (shapeBuilder_ == null) {
          shapeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              tensorflow.TensorShape.TensorShapeProto, tensorflow.TensorShape.TensorShapeProto.Builder, tensorflow.TensorShape.TensorShapeProtoOrBuilder>(
                  getShape(),
                  getParentForChildren(),
                  isClean());
          shape_ = null;
        }
        return shapeBuilder_;
      }

      private tensorflow.AllocationDescriptionOuterClass.AllocationDescription allocationDescription_ = null;
      private com.google.protobuf.SingleFieldBuilder<
          tensorflow.AllocationDescriptionOuterClass.AllocationDescription, tensorflow.AllocationDescriptionOuterClass.AllocationDescription.Builder, tensorflow.AllocationDescriptionOuterClass.AllocationDescriptionOrBuilder> allocationDescriptionBuilder_;
      /**
       * <code>optional .tensorflow.AllocationDescription allocation_description = 4;</code>
       *
       * <pre>
       * Information about the size and allocator used for the data
       * </pre>
       */
      public boolean hasAllocationDescription() {
        return allocationDescriptionBuilder_ != null || allocationDescription_ != null;
      }
      /**
       * <code>optional .tensorflow.AllocationDescription allocation_description = 4;</code>
       *
       * <pre>
       * Information about the size and allocator used for the data
       * </pre>
       */
      public tensorflow.AllocationDescriptionOuterClass.AllocationDescription getAllocationDescription() {
        if (allocationDescriptionBuilder_ == null) {
          return allocationDescription_ == null ? tensorflow.AllocationDescriptionOuterClass.AllocationDescription.getDefaultInstance() : allocationDescription_;
        } else {
          return allocationDescriptionBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .tensorflow.AllocationDescription allocation_description = 4;</code>
       *
       * <pre>
       * Information about the size and allocator used for the data
       * </pre>
       */
      public Builder setAllocationDescription(tensorflow.AllocationDescriptionOuterClass.AllocationDescription value) {
        if (allocationDescriptionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          allocationDescription_ = value;
          onChanged();
        } else {
          allocationDescriptionBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .tensorflow.AllocationDescription allocation_description = 4;</code>
       *
       * <pre>
       * Information about the size and allocator used for the data
       * </pre>
       */
      public Builder setAllocationDescription(
          tensorflow.AllocationDescriptionOuterClass.AllocationDescription.Builder builderForValue) {
        if (allocationDescriptionBuilder_ == null) {
          allocationDescription_ = builderForValue.build();
          onChanged();
        } else {
          allocationDescriptionBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .tensorflow.AllocationDescription allocation_description = 4;</code>
       *
       * <pre>
       * Information about the size and allocator used for the data
       * </pre>
       */
      public Builder mergeAllocationDescription(tensorflow.AllocationDescriptionOuterClass.AllocationDescription value) {
        if (allocationDescriptionBuilder_ == null) {
          if (allocationDescription_ != null) {
            allocationDescription_ =
              tensorflow.AllocationDescriptionOuterClass.AllocationDescription.newBuilder(allocationDescription_).mergeFrom(value).buildPartial();
          } else {
            allocationDescription_ = value;
          }
          onChanged();
        } else {
          allocationDescriptionBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .tensorflow.AllocationDescription allocation_description = 4;</code>
       *
       * <pre>
       * Information about the size and allocator used for the data
       * </pre>
       */
      public Builder clearAllocationDescription() {
        if (allocationDescriptionBuilder_ == null) {
          allocationDescription_ = null;
          onChanged();
        } else {
          allocationDescription_ = null;
          allocationDescriptionBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .tensorflow.AllocationDescription allocation_description = 4;</code>
       *
       * <pre>
       * Information about the size and allocator used for the data
       * </pre>
       */
      public tensorflow.AllocationDescriptionOuterClass.AllocationDescription.Builder getAllocationDescriptionBuilder() {
        
        onChanged();
        return getAllocationDescriptionFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .tensorflow.AllocationDescription allocation_description = 4;</code>
       *
       * <pre>
       * Information about the size and allocator used for the data
       * </pre>
       */
      public tensorflow.AllocationDescriptionOuterClass.AllocationDescriptionOrBuilder getAllocationDescriptionOrBuilder() {
        if (allocationDescriptionBuilder_ != null) {
          return allocationDescriptionBuilder_.getMessageOrBuilder();
        } else {
          return allocationDescription_ == null ?
              tensorflow.AllocationDescriptionOuterClass.AllocationDescription.getDefaultInstance() : allocationDescription_;
        }
      }
      /**
       * <code>optional .tensorflow.AllocationDescription allocation_description = 4;</code>
       *
       * <pre>
       * Information about the size and allocator used for the data
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          tensorflow.AllocationDescriptionOuterClass.AllocationDescription, tensorflow.AllocationDescriptionOuterClass.AllocationDescription.Builder, tensorflow.AllocationDescriptionOuterClass.AllocationDescriptionOrBuilder> 
          getAllocationDescriptionFieldBuilder() {
        if (allocationDescriptionBuilder_ == null) {
          allocationDescriptionBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              tensorflow.AllocationDescriptionOuterClass.AllocationDescription, tensorflow.AllocationDescriptionOuterClass.AllocationDescription.Builder, tensorflow.AllocationDescriptionOuterClass.AllocationDescriptionOrBuilder>(
                  getAllocationDescription(),
                  getParentForChildren(),
                  isClean());
          allocationDescription_ = null;
        }
        return allocationDescriptionBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:tensorflow.TensorDescription)
    }

    // @@protoc_insertion_point(class_scope:tensorflow.TensorDescription)
    private static final tensorflow.TensorDescriptionOuterClass.TensorDescription DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new tensorflow.TensorDescriptionOuterClass.TensorDescription();
    }

    public static tensorflow.TensorDescriptionOuterClass.TensorDescription getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TensorDescription>
        PARSER = new com.google.protobuf.AbstractParser<TensorDescription>() {
      public TensorDescription parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new TensorDescription(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<TensorDescription> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TensorDescription> getParserForType() {
      return PARSER;
    }

    public tensorflow.TensorDescriptionOuterClass.TensorDescription getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_tensorflow_TensorDescription_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_tensorflow_TensorDescription_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n2tensorflow/core/framework/tensor_descr" +
      "iption.proto\022\ntensorflow\032%tensorflow/cor" +
      "e/framework/types.proto\032,tensorflow/core" +
      "/framework/tensor_shape.proto\0326tensorflo" +
      "w/core/framework/allocation_description." +
      "proto\"\250\001\n\021TensorDescription\022#\n\005dtype\030\001 \001" +
      "(\0162\024.tensorflow.DataType\022+\n\005shape\030\002 \001(\0132" +
      "\034.tensorflow.TensorShapeProto\022A\n\026allocat" +
      "ion_description\030\004 \001(\0132!.tensorflow.Alloc" +
      "ationDescriptionb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          tensorflow.Types.getDescriptor(),
          tensorflow.TensorShape.getDescriptor(),
          tensorflow.AllocationDescriptionOuterClass.getDescriptor(),
        }, assigner);
    internal_static_tensorflow_TensorDescription_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tensorflow_TensorDescription_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_tensorflow_TensorDescription_descriptor,
        new java.lang.String[] { "Dtype", "Shape", "AllocationDescription", });
    tensorflow.Types.getDescriptor();
    tensorflow.TensorShape.getDescriptor();
    tensorflow.AllocationDescriptionOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
